spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: lmz
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8181